name: Deploy to Render

on:
  push:
    branches:
      - [cite_start]main # Chạy khi có code push vào nhánh main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger Render Deploy
        # Sử dụng curl để gọi Webhook của Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
